# Site settings
title: Your Name - AI Engineer
email: your.email@example.com
description: AI Engineer passionate about machine learning, deep learning, and innovative AI solutions.
baseurl: ""
url: "https://your-username.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Social media usernames
github_username: your-username
linkedin_username: your-linkedin
twitter_username: your-twitter

# Navigation
header_pages:
  - about.md
  - experience.md
  - education.md
  - projects.md
  - skills.md
  - courses.md
  - contact.md
